//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18331
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnimalMarketEngine.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TextsResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextsResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AnimalMarketEngine.Resources.TextsResource", typeof(TextsResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successful advertising: eat pork chops.
        /// </summary>
        internal static string AdvertisingPush {
            get {
                return ResourceManager.GetString("AdvertisingPush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successful advertising: eat organic Lamb.
        /// </summary>
        internal static string AdvertisingPushLamb {
            get {
                return ResourceManager.GetString("AdvertisingPushLamb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banks are speculating in the beef market.
        /// </summary>
        internal static string BanksSpeculationBeef {
            get {
                return ResourceManager.GetString("BanksSpeculationBeef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pig Disease Outbreak:  Pale Pig Syndrome.
        /// </summary>
        internal static string BiotinDeficiency {
            get {
                return ResourceManager.GetString("BiotinDeficiency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pig Disease Outbreak:  Porcine Reproductive &amp; Respiratory Syndrome (PRRS).
        /// </summary>
        internal static string BushFootFootRot {
            get {
                return ResourceManager.GetString("BushFootFootRot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sheep Disease Outbreak: Cache Valley Virus.
        /// </summary>
        internal static string CacheValleyVirus {
            get {
                return ResourceManager.GetString("CacheValleyVirus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calf, Cows.
        /// </summary>
        internal static string Calf {
            get {
                return ResourceManager.GetString("Calf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calf Scour.
        /// </summary>
        internal static string CalfScour {
            get {
                return ResourceManager.GetString("CalfScour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Festival Season people are buying more pork.
        /// </summary>
        internal static string FestivalSeason {
            get {
                return ResourceManager.GetString("FestivalSeason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Festival Season people are buying more sheep.
        /// </summary>
        internal static string FestivalSeasonSheep {
            get {
                return ResourceManager.GetString("FestivalSeasonSheep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pig Disease Outbreak: Foot-and-Mouth Disease.
        /// </summary>
        internal static string FootAndMouthDisease {
            get {
                return ResourceManager.GetString("FootAndMouthDisease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sheep Disease Outbreak: Footrot.
        /// </summary>
        internal static string Footrot {
            get {
                return ResourceManager.GetString("Footrot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pig Disease Outbreak:  Swine Influenza Virus (SI), Flu.
        /// </summary>
        internal static string Hypoglycaemia {
            get {
                return ResourceManager.GetString("Hypoglycaemia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lamb, Sheep.
        /// </summary>
        internal static string Lamb {
            get {
                return ResourceManager.GetString("Lamb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new cases of Mad cow disease.
        /// </summary>
        internal static string MadCowDisease {
            get {
                return ResourceManager.GetString("MadCowDisease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beef market crash, prices are falling.
        /// </summary>
        internal static string MarketCrash {
            get {
                return ResourceManager.GetString("MarketCrash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pig Disease Outbreak: Mulberry Heart Disease (vitamin E deficiency).
        /// </summary>
        internal static string MulberryHeartDiseasevitaminEdeficiency {
            get {
                return ResourceManager.GetString("MulberryHeartDiseasevitaminEdeficiency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pig.
        /// </summary>
        internal static string Pig {
            get {
                return ResourceManager.GetString("Pig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beef market has a lot of activity.
        /// </summary>
        internal static string PressureOnTheBeefMarket {
            get {
                return ResourceManager.GetString("PressureOnTheBeefMarket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pressure on the pig market.
        /// </summary>
        internal static string PressureOnThePigMarket {
            get {
                return ResourceManager.GetString("PressureOnThePigMarket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lamb, mutton market has a lot of activity.
        /// </summary>
        internal static string PressureOnTheSheepMarket {
            get {
                return ResourceManager.GetString("PressureOnTheSheepMarket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sheep Disease Outbreak: Foot-and-mouth disease.
        /// </summary>
        internal static string SheepFootandmouthdisease {
            get {
                return ResourceManager.GetString("SheepFootandmouthdisease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortage of beef.
        /// </summary>
        internal static string ShortageOfBeef {
            get {
                return ResourceManager.GetString("ShortageOfBeef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banks are speculating with the pig stocks.
        /// </summary>
        internal static string Speculation {
            get {
                return ResourceManager.GetString("Speculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pig Disease Outbreak:  Sunburn.
        /// </summary>
        internal static string Sunburn {
            get {
                return ResourceManager.GetString("Sunburn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sheep Disease Outbreak: White muscle disease.
        /// </summary>
        internal static string Whitemuscledisease {
            get {
                return ResourceManager.GetString("Whitemuscledisease", resourceCulture);
            }
        }
    }
}
